<?php
/**
 * Created by PhpStorm.
 * User: zhangxiang
 * Date: 2018/11/29
 * Time: 11:21 AM
 */

namespace app\index\controller;


use app\service\BookService;
use think\Request;

class Rank extends Base
{
    protected $bookService;
    protected function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $this->bookService = new BookService();
    }

    public function index(Request $request){
        $most_click_week = cache('most_click_week');
        if (!$most_click_week){
            $most_click_week = $this->bookService->getBooksByTime(10,'click',date("Y-m-d",strtotime("-7 day")));
            cache('most_click_week',$most_click_week);
        }
        $most_click_month = cache('most_click_month');
        if (!$most_click_month){
            $most_click_month = $this->bookService->getBooksByTime(10,'click',date("Y-m-d",strtotime("-30 day")));
            cache('most_click_month',$most_click_month);
        }
        $most_click = cache('most_click');
        if (!$most_click){
            $most_click = $this->bookService->getBooksByTime(10,'click','1900-01-01');
            cache('most_click',$most_click);
        }
        $newest_week = cache('newest_week');
        if (!$newest_week){
            $newest_week = $this->bookService->getBooksByTime(10,'id',date("Y-m-d",strtotime("-7 day")));
            cache('newest_week',$newest_week);
        }
        $newest_month = cache('newest_month');
        if (!$newest_month){
            $newest_month = $this->bookService->getBooksByTime(10,'id',date("Y-m-d",strtotime("-30 day")));
            cache('newest_month',$newest_month);
        }
        $newest = cache('newest');
        if (!$newest){
            $newest = $this->bookService->getBooksByTime(10,'id','1900-01-01');
            cache('newest',$newest);
        }
        $update_week = cache('update_week');
        if (!$update_week){
            $update_week = $this->bookService->getBooksByTime(10,'last_time',date("Y-m-d",strtotime("-7 day")));
            cache('update_week',$update_week);
        }
        $update_month = cache('update_month');
        if (!$update_month){
            $update_month = $this->bookService->getBooksByTime(10,'last_time',date("Y-m-d",strtotime("-30 day")));
            cache('update_month',$update_month);
        }
        $update = cache('rank_update');{
            $update = $this->bookService->getBooksByTime(10,'last_time','1900-01-01');
            cache('rank_update',$update);
        }
        $this->assign([
            'most_click_week' => $most_click_week,
            'most_click_month' => $most_click_month,
            'most_click' => $most_click,
            'newest_week' => $newest_week,
            'newest_month' => $newest_month,
            'newest' => $newest,
            'update_week' => $update_week,
            'update_month' => $update_month,
            'update' => $update,
            'header_title' => '排行榜',
        ]);
        return view($this->tpl);
    }

    public function lists(){
        $this->assign('header_title','排行榜');
        return view();
    }
}